wip

diff --git a/bin/ckgen b/bin/ckgen
--- a/bin/ckgen
+++ b/bin/ckgen
@@ -12,11 +12,24 @@ for i in tmux rsync parallel; do
 	fi
 done
 
+function esm_parse() {
+	local t e a s
+
+	t=( ${1//[\/:]/ } )
+	e=${t[0]}
+	if [[ ${#t[*]} -gt 2 ]]; then
+		a=${t[1]}
+		s=${t[2]}
+	else
+		s=${t[1]}
+	fi
+
+	echo "'$e'" "'$a'" "'$s'"
+}
+
 TMUX=1
 START=1
-SHARDS_PC=1
-SHARDS_PV=1
-SHARDS_MAX=1
+SHARDS=1
 CORES=$(awk '/cpu cores/ && !seen[$NF]++ { print $NF }' /proc/cpuinfo)
 THREADS=$(egrep -c '^processor[[:space:]]+' /proc/cpuinfo)
 JOBS=$CORES
@@ -25,10 +38,10 @@ BUILD=$SELF.build
 OUT=$SELF.out
 FALLOUT4_PC_ARCHIVE="Fallout4 - ckgen_pc.ba2"
 
-while getopts "j:s:S:t:A:Ppam" opt; do
+while getopts "j:s:S:t:A:PpamM" opt; do
         case $opt in
 	j) JOBS="$OPTARG" ;;
-	s) SHARDS_PC="$OPTARG"; SHARDS_PV="$OPTARG" ;;
+	s) SHARDS="$OPTARG" ;;
 	S) START="$OPTARG" ;;
 	t) TMUX="$OPTARG" ;;
 	A) FALLOUT4_PC_ARCHIVE="$OPTARG" ;;
@@ -36,14 +49,24 @@ while getopts "j:s:S:t:A:Ppam" opt; do
 	P) PRESERVE_OUT=1 ;;
 	a) ARCHIVE=1 ;;
 	m) MERGE=1 ;;
+	M) MANUAL=1 ;;
 	?) exit -1 ;;
         esac
 done; shift $((OPTIND - 1))
 
 PROFILE="$1"; shift
 MODE="$1"; shift
-TYPE="$1"; shift
-AREA="$1"; shift
+if ((!MANUAL)); then
+	TYPE="$1"; shift
+	AREA="$1"; shift
+else
+	TYPE="clean"
+	AREA="main"
+fi
+
+MODE=( ${MODE//,/ } )
+AREA=( ${AREA//,/ } )
+ESM=( "$@" )
 
 if [[ -z "$PROFILE" ]]; then
 	echo "No profile specified" 1>&2
@@ -56,16 +79,15 @@ elif [[ "$TYPE" != "clean" && "$TYPE" != "filtered" ]]; then
 	exit -1
 fi
 
-MODE=( ${MODE//,/ } )
-AREA=( ${AREA//,/ } )
-ESM=( "$@" )
+SHARDS_MAX=$SHARDS
 
 for esm in "${ESM[@]}"; do
-	t=( ${esm//\// } ); e=${t[0]}; s=${t[1]}
-	if [[ "$e" =~ [[:space:]] ]]; then
-		echo "Plugins cannot have spaces in them (CK limitation)" 1>&2
+	eval ep=( $(esm_parse $esm) ); esm=${ep[0]}; a=${ep[1]}; s=${ep[2]}
+
+	if [[ "$esm" =~ [[:space:]] ]]; then
+		echo "Plugins cannot have spaces in them (CK limitation): '$esm'" 1>&2
 		exit -1
-	elif [[ "$e" == "Fallout4.esm" ]]; then
+	elif [[ "$esm" == "Fallout4.esm" ]]; then
 		FALLOUT4_ESM=1
 	fi
 
@@ -75,31 +97,14 @@ done
 for mode in ${MODE[*]}; do
 	# Could not parse command line properly.  Should be -GeneratePreCombined:<ESMFilename> [clean,filtered] [all,main,ints,other] [currentset(1-totalsetcount)] [totalsetcount]
 	# Could not parse command line properly.  Should be -GeneratePreVisData:<ESMFilename> [clean,filtered] [all,main,ints,other] [currentset(1-totalsetcount)] [totalsetcount]
-	if [[ "$mode" == "precombined" ]]; then
-		if [[ "$type" == "clean" ]]; then
-			echo "Warning: generating data of type 'clean' cannot be run in parallel due to inability to merge shared geometry data (PSG/CSG)" 1>&2
-			SHARDS_PC=1
-			SHARDS_FORCE=1
-		fi
-		for area in ${AREA[*]}; do
-			if [[ "$area" == "all" ]]; then
-				echo "Warning: area of type 'all' does not parallelize with precombines (CK limitation)" 1>&2
-				AREA=( 'all' )
-				SHARDS_PC=1
-				SHARDS_FORCE=1
-				break
-			fi
-		done
-	elif [[ "$mode" != "previs" ]]; then
-		echo "Invalid mode: $mode" 1>&2
-		exit -1;
-	fi
+	[[ "$mode" == "precombined" || "$mode" == "previs" ]] && continue
+
+	echo "Invalid mode: $mode" 1>&2
+	exit -1;
 done
 
 for area in ${AREA[*]}; do
-	if [[ "$area" == "all" || "$area" == "main" || "$area" == "ints" || "$area" == "other" ]]; then
-		continue
-	fi
+	[[ "$area" == "all" || "$area" == "main" || "$area" == "ints" || "$area" == "other" ]] && continue
 
 	echo "Invalid area: $area" 1>&2
 	exit -1;
@@ -129,7 +134,7 @@ if ((!PRESERVE)); then
 		set -e
 
 		# Hardlink base directory contents to per-build directories
-		rsync -aSPH \
+		rsync -aSH \
 			--exclude "$OUT" \
 			--exclude "$BUILD" \
 			--exclude log.txt \
@@ -141,11 +146,12 @@ if ((!PRESERVE)); then
 			--exclude PreVis.esp \
 			--exclude PreCombined \
 			--exclude Vis \
+			--exclude Scripts \
 			--link-dest="$SRC" "$SRC"/ "$BUILD/$i"/ \
 			|| exit -1
 
 		# Hardcopy CK ini files
-		rsync -aSPH "$SRC"/CreationKit*.ini "$BUILD/$i"/ || exit -1
+		rsync -aSH "$SRC"/CreationKit*.ini "$BUILD/$i"/ || exit -1
 
 		for j in "$BUILD/$i/CreationKit.ini" "$BUILD/$i/CreationKitCustom.ini"; do
 			[[ -f "$j" ]] || continue
@@ -224,7 +230,10 @@ ck_wrap() {
 	cur="$1"; shift
 	max="$1"; shift
 	job="$1"; shift
+	manual="$1"; shift
 	wcur=$(printf "%02d" $cur)
+
+	[[ "$esm" == "Fallout4.esm" ]] && pc_archive_only=1
 
 	mkdir -p "$bdir/$esm" || { touch "$bdir/precombined.$wcur.error"; exit -1; }
 
@@ -232,11 +241,12 @@ ck_wrap() {
 	# directory, regenerate it with CK, and then move the results
 	# to the output directory.
 	if [[ "$mode" == "precombined" ]]; then
+		((manual)) || CKARGS=( -generateprecombined:"$esm" $type $area $cur $max )
 		rm -rf "$bdir/$job/Data/Meshes/PreCombined" "$bdir/$job/Data/CombinedObjects.esp" "$bdir/$esm/PreCombined.$area.$wcur" \
-			&& (cd "$bdir/$job" && ./CreationKit.exe -generateprecombined:"$esm" $type $area $cur $max) \
+			&& (cd "$bdir/$job" && ./CreationKit.exe ${CKARGS[*]}) \
 			&& (
 				[[ -d "$bdir/$job/Data/Meshes/PreCombined" ]] && mv "$bdir/$job/Data/Meshes/PreCombined" "$bdir/$esm/PreCombined.$area.$wcur"
-				[[ -f "$bdir/$job/Data/CombinedObjects.esp" ]] && mv "$bdir/$job/Data/CombinedObjects.esp" "$bdir/$esm/CombinedObjects.$area.$wcur.esp"
+				[[ -f "$bdir/$job/Data/CombinedObjects.esp" ]] && mv "$bdir/$job/Data/CombinedObjects.esp" "$bdir/$esm/$esm.precombine_merge.$area.$wcur.esp"
 			) \
 			|| touch "$bdir/precombined.$esm.$area.$wcur.error"
 	elif [[ "$mode" == "previs" ]]; then
@@ -248,22 +258,31 @@ ck_wrap() {
 		# However, since loose files override archives, the actual
 		# directory needs to be moved aside so CreationKit doesn't
 		# parse the loose files.
-		if [[ "$esm" == "Fallout4.esm" ]]; then
-			mv "$bdir/$job/Data/Meshes/PreCombined" "$bdir/$job/Data/Meshes/.PreCombined"
+		if ((pc_archive_only)) && [[ -d "$bdir/$job/Data/Meshes/PreCombined" ]]; then
+			if [[ -d "$bdir/$job/Data/Meshes/.PreCombined" ]]; then
+				echo "$bdir/$job/Data/Meshes/.PreCombined: already exists!"
+				exit -1
+			fi
+			mv -T "$bdir/$job/Data/Meshes/PreCombined" "$bdir/$job/Data/Meshes/.PreCombined"
 		fi
 
+		((manual)) || CKARGS=( -generateprevisdata:"$esm" $type $area $cur $max )
 		rm -rf "$bdir/$job/Data/Vis" "$bdir/$job/Data/PreVis.esp" "$bdir/$esm/Vis.$area.$wcur" \
-			&& (cd "$bdir/$job" && ./CreationKit.exe -generateprevisdata:"$esm" $type $area $cur $max) \
+			&& (cd "$bdir/$job" && ./CreationKit.exe ${CKARGS[*]}) \
 			&& (
 				[[ -d "$bdir/$job/Data/Vis" ]] && mv "$bdir/$job/Data/Vis" "$bdir/$esm/Vis.$area.$wcur"
-				[[ -f "$bdir/$job/Data/PreVis.esp" ]] && mv "$bdir/$job/Data/PreVis.esp" "$bdir/$esm/PreVis.$area.$wcur.esp"
+				[[ -f "$bdir/$job/Data/PreVis.esp" ]] && mv "$bdir/$job/Data/PreVis.esp" "$bdir/$esm/$esm.previs_merge.$area.$wcur.esp"
 			) \
 			|| touch "$bdir/previs.$esm.$area.$wcur.error"
 
 		# If precombines have been moved aside, restore the loose
 		# files in case another job uses this build slot.
-		if [[ -d "$bdir/$job/Data/Meshes/.PreCombined" ]]; then
-			mv "$bdir/$job/Data/Meshes/.PreCombined" "$bdir/$job/Data/Meshes/PreCombined"
+		if ((pc_archive_only)) && [[ -d "$bdir/$job/Data/Meshes/.PreCombined" ]]; then
+			if [[ -d "$bdir/$job/Data/Meshes/PreCombined" ]]; then
+				echo "$bdir/$job/Data/Meshes/PreCombined: already exists!"
+				exit -1
+			fi
+			mv -T "$bdir/$job/Data/Meshes/.PreCombined" "$bdir/$job/Data/Meshes/PreCombined"
 		fi
 	fi
 
@@ -284,20 +303,34 @@ for mode in "${MODE[@]}"; do
 	if [[ "$mode" == "previs" ]]; then
 		find "$BUILD" -type d -name '[0-9]*' -prune -print0 \
 			| CYGWIN=winsymlinks:nativestrict xargs -I{} -r0 ln -sfT "$PWD/Data/Meshes/PreCombined" "$PWD/{}/Data/Meshes/PreCombined"
-		SHARDS=$SHARDS_PV
-	elif [[ "$mode" == "precombined" ]]; then
-		SHARDS=$SHARDS_PC
 	fi
 
 	CMDS=$(
-	for esm in ${ESM[*]}; do
-		t=( ${esm//\// } ); e=${t[0]}; s=${t[1]}
-		if ((!s || SHARDS_FORCE)); then
-			s=$SHARDS
-		fi
+		for esm in ${ESM[*]}; do
+			eval ep=( $(esm_parse $esm) ); esm=${ep[0]}; a=${ep[1]}; s=${ep[2]}
 
-		parallel -r -j1 echo ck_wrap $BUILD $mode $TYPE {1} {2} {3} $s ::: $e ::: ${AREA[*]} ::: $(seq -s ' ' $START $s)
-	done)
+			[[ -n $a ]] && atmp=( ${a//,/ } ) || atmp=( ${AREA[*]} )
+			[[ -n $s ]] || s=$SHARDS
+
+			for area in ${atmp[*]}; do
+				if [[ "$area" != "main" && "$area" != "ints" ]]; then
+					echo "$esm: Warning: area of '$area' does not parallelize (CK limitation)" 1>&2
+					s=1
+				elif [[ "$area" != "all" && "$mode" == "precombined" && "$type" == "clean" ]]; then
+					echo "$esm: Error: generating precombines of type 'clean' cannot be run in parallel or in sub-areas due to inability to merge shared geometry data (PSG/CSG)" 1>&2
+					exit -1
+				fi
+
+				parallel -r -j1 echo "ck_wrap $BUILD $mode $TYPE {1} {2} {3} $s" ::: $esm ::: $area ::: $(seq -s ' ' $START $s)
+			done
+		done
+	)
+
+	if ((MANUAL)); then
+		PFLAGS="--delay 4 --lb -vr -j $JOBS"
+	else
+		PFLAGS="--eta --shuf --lb -vr -j $JOBS"
+	fi
 
 	# Note: final 'read' commands are to prevent tmux from closing each sub-window
 	if ((TMUX)); then
@@ -306,50 +339,54 @@ for mode in "${MODE[@]}"; do
 			split -p 40 \
 			"tail -qn 10000 -s 0.1 -F ${LOGS[*]} 2>/dev/null | egrep --line-buffered -v -i gen.*for.*cell | cat -n" ';' \
 			split -p 50 \
-			"echo '$CMDS' | tee /tmp/parallel.in | parallel --eta --shuf --lb -vr -j $JOBS {} {%}; read"
+			"echo '$CMDS' | tee /tmp/parallel.in | parallel $PFLAGS --lb -vr -j $JOBS '{} {%} $MANUAL'; read" ';' \
+			set-option status off
 	else
-		echo "$CMDS" | parallel --eta --shuf --lb -vr -j $JOBS {} {%} || exit -1
+		echo "$CMDS" | parallel $PFLAGS "{} {%} $MANUAL" || exit -1
 	fi
 
 	for esm in ${ESM[*]}; do
-		t=( ${esm//\// } ); e=${t[0]}; s=${t[1]}
+		eval ep=( $(esm_parse $esm) ); esm=${ep[0]}; a=${ep[1]}; s=${ep[2]}
 
 		# XXX: this is a mv which could affect a previs after a precombine if an archive isn't involved inbetween
 		if [[ "$mode" == "precombined" ]]; then
-			h=0; for i in $(ls -d "$BUILD/$e/PreCombined".* 2>/dev/null); do
-				((h++)) || echo "Moving precombined for $e..." 1>&2
-				mkdir -p "$OUT/$e/Data/Meshes/PreCombined"
-				rsync --remove-source-files -aS "$i"/ "$OUT/$e/Data/Meshes/PreCombined"/ || true
+			h=0; for i in $(ls -d "$BUILD/$esm/PreCombined".* 2>/dev/null); do
+				((h++)) || echo "$esm: Moving precombined..." 1>&2
+				mkdir -p "$OUT/$esm/Meshes/PreCombined"
+				rsync --remove-source-files -aS "$i"/ "$OUT/$esm/Meshes/PreCombined"/ || true
 			done
 		elif [[ "$mode" == "previs" ]]; then
-			h=0; for i in $(ls -d "$BUILD/$e/Vis".* 2>/dev/null); do
-				((h++)) || echo "Moving previs for $e..." 1>&2
-				mkdir -p "$OUT/$e/Data/Vis"
-				rsync --remove-source-files -aS "$i"/ "$OUT/$e/Data/Vis"/ || true
+			h=0; for i in $(ls -d "$BUILD/$esm/Vis".* 2>/dev/null); do
+				((h++)) || echo "$esm: Moving previs..." 1>&2
+				mkdir -p "$OUT/$esm/Vis"
+				rsync --remove-source-files -aS "$i"/ "$OUT/$esm/Vis"/ || true
 			done
 		fi
 
-		if [[ -d "$BUILD/$e" ]]; then
-			echo "Moving plugins for $e..." 1>&2
-			mkdir -p "$OUT/$e/plugins"
-			find "$BUILD/$e" -type f -name 'CombinedObjects.*.esp' -o -name 'PreVis.*.esp' -print0 | xargs -r0 mv -nt "$OUT/$e/plugins"
-			find "$BUILD/$e" -type d -empty -print0 | xargs -r0 rmdir --ignore-fail-on-non-empty
+		if [[ -d "$BUILD/$esm" ]]; then
+			echo "$esm: Moving plugins..." 1>&2
+
+			mkdir -p "$OUT/$esm"
+			find "$BUILD/$esm" -type f -name '*.esp' -print0 | xargs -r0 mv -nt "$OUT/$esm"
+			find "$BUILD/$esm" -type d -empty -print0 | xargs -r0 rmdir --ignore-fail-on-non-empty
 		fi
 
+		# hardlink plugins into Data?
 		if ((MERGE)); then
-			echo "Merging plugins for $e..." 1>&2
+			echo "$esm: Merging plugins..." 1>&2
 
 			# XXX: Plugins might have to be in Data first
 			# Could not parse command line properly.  Should be -CheckInPlugin:<PluginFilename> <ESMFilename>
-			find "$OUT/$e/plugins" -type f -name '*.esp' -print0 \
-				| xargs -I{} -r0 -n1 ./CreationKit.exe -checkinplugin:{} $e
+			find "$OUT/$esm" -type f -name '*.esp' -print0 \
+				| xargs -I{} -r0 -n1 ./CreationKit.exe -checkinplugin:{} $esm
 		fi
 
+		# hardlink archive into Data?
 		if ((ARCHIVE)); then
-			echo "Archiving data for $e..." 1>&2
+			echo "$esm: Archiving data..." 1>&2
 
 			# Output data will contain precombined and/or previs data only at this point
-			Tools/Archive2/Archive2.exe "$OUT/$e/Data" -c="$OUT/$e/${esm/.esm} - ckgen.ba2"
+			Tools/Archive2/Archive2.exe "$OUT/$esm"/{Vis,Meshes/PreCombined} -c="$OUT/$esm/${esm/.esm} - ckgen.ba2"
 		fi
 
 	done
