wip

diff --git a/bin/ckgen b/bin/ckgen
--- a/bin/ckgen
+++ b/bin/ckgen
@@ -13,34 +13,33 @@ for i in tmux rsync parallel; do
 done
 
 TMUX=1
-JOBS=1
 START=1
-SHARDS=32
+SHARDS=8
+CORES=$(awk '/cpu cores/ && !seen[$NF]++ { print $NF }' /proc/cpuinfo)
+JOBS=$CORES
 SELF=$(basename $0)
 BUILD=$SELF.build
 OUT=$SELF.out
+FALLOUT4_PC_ARCHIVE="Fallout4 - ckgen_pc.ba2"
 
-while getopts "a:j:m:s:S:t:p" opt; do
+while getopts "j:s:S:t:Ppam" opt; do
         case $opt in
-	a) ARCHIVE="$OPTARG" ;;
 	j) JOBS="$OPTARG" ;;
-	m) MERGE="$OPTARG" ;;
 	s) SHARDS="$OPTARG" ;;
 	S) START="$OPTARG" ;;
 	t) TMUX="$OPTARG" ;;
 	p) PRESERVE=1 ;;
+	P) PRESERVE_OUT=1 ;;
+	a) ARCHIVE=1 ;;
+	m) MERGE=1 ;;
 	?) exit -1 ;;
         esac
 done; shift $((OPTIND - 1))
 
 PROFILE="$1"; shift
 MODE="$1"; shift
-ESM="$(basename $1)"; shift
 TYPE="$1"; shift
 AREA="$1"; shift
-
-MODE=( ${MODE//,/ } )
-AREA=( ${AREA//,/ } )
 
 if [[ -z "$PROFILE" ]]; then
 	echo "No profile specified" 1>&2
@@ -48,27 +47,37 @@ if [[ -z "$PROFILE" ]]; then
 elif [[ ! -d "$PROGDIR/Fallout 4.$PROFILE" ]]; then
 	echo "$PROGDIR/Fallout 4.$PROFILE does not exist" 1>&2
 	exit -1
-elif [[ "$ESM" =~ [[:space:]] ]]; then
-	echo "Plugins cannot have spaces in them (CK limitation)" 1>&2
-	exit -1
 elif [[ "$TYPE" != "clean" && "$TYPE" != "filtered" ]]; then
 	echo "Invalid type: $TYPE" 1>&2
 	exit -1
 fi
 
-for mode in ${MODE[*]}; do
-	[[ "$mode" == "precombined" || "$mode" == "previs" ]] && continue
+MODE=( ${MODE//,/ } )
+AREA=( ${AREA//,/ } )
+ESM=( "$@" )
 
-	echo "Invalid mode: $mode" 1>&2
-	exit -1;
+for esm in "${ESM[@]}"; do
+	if [[ "$esm" =~ [[:space:]] ]]; then
+		echo "Plugins cannot have spaces in them (CK limitation)" 1>&2
+		exit -1
+	elif [[ "$esm" == "Fallout4.esm" ]]; then
+		FALLOUT4_ESM=1
+	fi
 done
 
-# Could not parse command line properly.  Should be -GeneratePreCombined:<ESMFilename> [clean,filtered] [all,main,ints,other] [currentset(1-totalsetcount)] [totalsetcount]
-# Could not parse command line properly.  Should be -GeneratePreVisData:<ESMFilename> [clean,filtered] [all,main,ints,other] [currentset(1-totalsetcount)] [totalsetcount]
-if [[ "$MODE" == "precombined" && "$TYPE" == "clean" ]]; then
-	echo "Warning: generating data of type 'clean' cannot be run in parallel due to inability to merge shared geometry data (PSG/CSG)" 1>&2
-	SHARDS=1
-fi
+for mode in ${MODE[*]}; do
+	if [[ "$mode" != "precombined" && "$mode" != "previs" ]]; then
+		echo "Invalid mode: $mode" 1>&2
+		exit -1;
+	fi
+
+	# Could not parse command line properly.  Should be -GeneratePreCombined:<ESMFilename> [clean,filtered] [all,main,ints,other] [currentset(1-totalsetcount)] [totalsetcount]
+	# Could not parse command line properly.  Should be -GeneratePreVisData:<ESMFilename> [clean,filtered] [all,main,ints,other] [currentset(1-totalsetcount)] [totalsetcount]
+	if [[ "$mode" == "precombined" && "$type" == "clean" ]]; then
+		echo "Warning: generating data of type 'clean' cannot be run in parallel due to inability to merge shared geometry data (PSG/CSG)" 1>&2
+		SHARDS=1
+	fi
+done
 
 for area in ${AREA[*]}; do
 	if [[ "$area" == "all" ]]; then
@@ -86,40 +95,98 @@ done
 
 cd "$PROGDIR/Fallout 4.$PROFILE"
 
-OUT="$OUT/$ESM"
-BUILD="$BUILD/$ESM"
-
-if ((!PRESERVE)); then
+if ((!PRESERVE_OUT)); then
 	echo "Removing previous output data..." 1>&2
 	rm -rf "$OUT" && mkdir -p "$OUT"
-
+fi
+if ((!PRESERVE)); then
 	echo "Removing previous build data..." 1>&2
 	rm -rf "$BUILD" && mkdir -p "$BUILD"
 
+	for mode in ${MODE[*]}; do
+		if ((FALLOUT4_ESM)) && [[ "$mode" == "previs" && ! -f "Data/$FALLOUT4_PC_ARCHIVE" ]]; then
+			echo "Building precombined archive for Fallout4.esm" 1>&2
+			Tools/Archive2/Archive2.exe Data/Meshes/PreCombined -c="Data/$FALLOUT4_PC_ARCHIVE"
+		fi
+	done
+
 	echo "Cloning build directories (hardlinks)..." 1>&2
-	for i in $(parallel --seqreplace _ "echo \$(((_ % $JOBS) + 1))" ::: ${AREA[*]} ::: $(seq -s ' ' $START $SHARDS) | sort -u); do
+	for i in $(parallel --seqreplace _ "echo \$(((_ % $JOBS) + 1))" ::: ${ESM[*]} ::: ${AREA[*]} ::: $(seq -s ' ' $START $SHARDS) | sort -u); do
 	(
+
 		# Hardlink base directory contents to per-build directories
-		rsync -avSPH \
+		rsync -aSPH \
 			--exclude "$BUILD" \
 			--exclude EditorWarnings.txt \
 			--exclude output.tome \
 			--exclude input.scene \
 			--exclude CombinedObjects.esp \
 			--exclude PreVis.esp \
-			--exclude PreCombined \
 			--exclude Vis \
 			--link-dest="$PWD" "$PWD"/ "$BUILD/$i"/ \
 			|| exit -1
 
-		# Temporarily disable version control for builds
+#			--exclude PreCombined \
+
+		# Hardcopy CK ini files
+		rsync -aSPH "$PWD"/CreationKit*.ini "$BUILD/$i"/ || exit -1
+
 		for j in "$BUILD/$i/CreationKit.ini" "$BUILD/$i/CreationKitCustom.ini"; do
 			if [[ -f "$j" ]] && grep -q 'bUseVersionControl=1' "$j"; then
+				# Nuke version control directory to prevent CK from prompting that VC is disabled
 				if [[ -d "$BUILD/$i/Data/Merging" ]]; then
 					find "$BUILD/$i/Data/Merging" -type f -name '*.esm' -print0 | xargs -r0 mv -t "$BUILD/$i/Data"
 					rm -rf "$BUILD/$i/Data/Merging"
 				fi
-				sed -ie 's#bUseVersionControl=1#bUseVersionControl=0#g' "$j"
+
+				# Enable multiple instances (so multiple copies can be run in parallel)
+				# Disable version control (so inability to check out a cell isn't an issue)
+				# Disable stopping on "important" warnings (so combined data warnings don't stop previs generation)
+				# Keep plugins that are merged with -checkinplugin (otherwise records merged and removed from the plugin)
+				# Set umbra threads to core count (default is 4)
+				# Force a few other previs related settings explicitly (even though they're the same as default)
+				#
+				# iMaxUmbraBakeThreads=16
+				# bExportSceneOnUmbraGenerate=0
+				# bExportTomeOnUmbraGenerate=0
+				# bGeneratePreCombinedGeometryPreVis=1
+				# bKeepPluginWhenMerging=1
+				# bHideImportantWarnings=1
+				# bUseVersionControl=0
+				#
+				awk -v cores=$CORES -v fo4pca="$FALLOUT4_PC_ARCHIVE" '
+                                { 
+                                        if (match($0, "^\\[([^\\]]+)\\]", a)) {
+                                                section=a[1];
+                                                slist[++slidx]=section;
+                                        } else if ($0 !~ /^$/ && match($0, "^([^=;]+) ?= ?(.+)$", a)) {
+                                                shash[section][a[1]]=a[2];
+                                        }
+                                }END{
+                                        shash["General"]["iMaxUmbraBakeThreads"]=cores;
+                                        shash["General"]["bExportSceneOnUmbraGenerate"]=0;
+                                        shash["General"]["bExportTomeOnUmbraGenerate"]=0;
+                                        shash["General"]["bGeneratePreCombinedGeometryPreVis"]=1;
+                                        shash["General"]["bKeepPluginWhenMerging"]=1;
+                                        shash["General"]["bHideImportantWarnings"]=1;
+                                        shash["General"]["bUseVersionControl"]=0;
+                                        shash["Archive"]["bInvalidateOlderFiles"]=1;
+                                        shash["Archive"]["sResourceDataDirsFinal"]="";
+					if (fo4pca)
+						shash["Archive"]["SResourceArchiveList"]=sprintf("Fallout4 - Voices.ba2, Fallout4 - Interface.ba2, Fallout4 - Meshes.ba2, Fallout4 - MeshesExtra.ba2, Fallout4 - Misc.ba2, Fallout4 - Shaders.ba2, Fallout4 - Sounds.ba2, Fallout4 - Materials.ba2, %s", fo4pca);
+
+                                        for (i = 1; i <= slidx; i++) {
+                                                section=slist[i];
+                                                printf("%s[%s]\r\n", i > 1 ? "\r\n" : "", section) >> "/dev/stderr";
+
+                                                asorti(shash[section], ss_src);
+
+                                                for (j = 1; j <= length(ss_src); j++) {
+                                                        hk = ss_src[j];
+                                                        printf("%s=%s\r\n", hk, shash[section][hk]) >> "/dev/stderr";
+                                                }
+                                        }
+                                }' "$j" > "$j.tmp" && mv "$j.tmp" "$j"
 			fi
 		done
 	) &
@@ -135,8 +202,8 @@ fi
 ck_wrap() {
 	bdir="$1"; shift
 	mode="$1"; shift
-	esm="$1"; shift
 	type="$1"; shift
+	esm="$1"; shift
 	area="$1"; shift
 	cur="$1"; shift
 	max="$1"; shift
@@ -147,20 +214,44 @@ ck_wrap() {
 	# directory, regenerate it with CK, and then move the results
 	# to the output directory.
 	if [[ "$mode" == "precombined" ]]; then
-		rm -rf "$bdir/$job/Data/Meshes/PreCombined" \
+		rm -rf "$bdir/$job/Data/Meshes/PreCombined" "$bdir/$job/Data/CombinedObjects.esp" "$bdir/$esm/PreCombined.$area.$wcur" \
 			&& (cd "$bdir/$job" && ./CreationKit.exe -generateprecombined:"$esm" $type $area $cur $max) \
-			&& mv "$bdir/$job/Data/Meshes/PreCombined" "$bdir/PreCombined.$area.$wcur" \
-			&& mv "$bdir/$job/Data/CombinedObjects.esp" "$bdir/CombinedObjects.$area.$wcur.esp" \
+			&& mkdir -p "$bdir/$esm" \
+			&& (
+				[[ -d "$bdir/$job/Data/Meshes/PreCombined" ]] && mv "$bdir/$job/Data/Meshes/PreCombined" "$bdir/$esm/PreCombined.$area.$wcur"
+				[[ -f "$bdir/$job/Data/CombinedObjects.esp" ]] && mv "$bdir/$job/Data/CombinedObjects.esp" "$bdir/$esm/CombinedObjects.$area.$wcur.esp"
+			) \
 			|| touch $bdir/precombined.$wcur.error
 	elif [[ "$mode" == "previs" ]]; then
-		rm -rf "$bdir/$job/Data/Vis" \
+		# Special hack for Fallout4.esm due to limitations in CK
+		# around the maximum number of cached file handles involved
+		# with loose files. Since Data/Meshes/PreCombined usually
+		# contains over 100k files for a full generation an archive
+		# needs to be used for precombines (via CreationKit.ini).
+		# However, since loose files override archives, the actual
+		# directory needs to be moved aside so CreationKit doesn't
+		# parse the loose files.
+		if [[ "$esm" == "Fallout4.esm" ]]; then
+			mv "$bdir/$job/Data/Meshes/PreCombined" "$bdir/$job/Data/Meshes/.PreCombined"
+		fi
+
+		rm -rf "$bdir/$job/Data/Vis" "$bdir/$job/Data/PreVis.esp" "$bdir/$esm/Vis.$area.$wcur" \
 			&& (cd "$bdir/$job" && ./CreationKit.exe -generateprevisdata:"$esm" $type $area $cur $max) \
-			&& mv "$bdir/$job/Data/Vis" "$bdir/Vis.$area.$wcur" \
-			&& mv "$bdir/$job/Data/PreVis.esp" "$bdir/PreVis.$area.$wcur.esp" \
+			&& mkdir -p "$bdir/$esm" \
+			&& (
+				[[ -d "$bdir/$job/Data/Vis" ]] && mv "$bdir/$job/Data/Vis" "$bdir/$esm/Vis.$area.$wcur"
+				[[ -f "$bdir/$job/Data/PreVis.esp" ]] && mv "$bdir/$job/Data/PreVis.esp" "$bdir/$esm/PreVis.$area.$wcur.esp"
+			) \
 			|| touch $bdir/previs.$wcur.error
+
+		# If precombines have been moved aside, restore the loose
+		# files in case another job uses this build slot.
+		if [[ -d "$bdir/$job/Data/Meshes/.PreCombined" ]]; then
+			mv "$bdir/$job/Data/Meshes/.PreCombined" "$bdir/$job/Data/Meshes/PreCombined"
+		fi
 	fi
 
-	mv "$bdir/$job/EditorWarnings.txt" "$bdir/EditorWarnings.$mode.$area.$wcur.txt"
+	mv "$bdir/$job/EditorWarnings.txt" "$bdir/$esm/EditorWarnings.$mode.$type.$area.$wcur.txt"
 }
 export -f ck_wrap
 
@@ -176,37 +267,46 @@ for mode in "${MODE[@]}"; do
 			split -p 40 \
 			"tail -qn 10000 -s 0.1 -F ${LOGS[*]} 2>/dev/null | egrep --line-buffered -v -i gen.*for.*cell | cat -n" ';' \
 			split -p 50 \
-			"parallel --eta --shuf --lb -vr -j $JOBS ck_wrap $BUILD $mode $ESM $TYPE {1} {2} $SHARDS {%} ::: ${AREA[*]} ::: $(seq -s ' ' $START $SHARDS); read"
+			"parallel --eta --shuf --lb -vr -j $JOBS ck_wrap $BUILD $mode $TYPE {1} {2} {3} $SHARDS {%} ::: ${ESM[*]} ::: ${AREA[*]} ::: $(seq -s ' ' $START $SHARDS); read"
 	else
-		parallel --eta --shuf --lb -vr -j $JOBS ck_wrap $BUILD $mode $ESM $TYPE {1} {2} $SHARDS {%} ::: ${AREA[*]} ::: $(seq -s ' ' $START $SHARDS) || exit -1
+		parallel --eta --shuf --lb -vr -j $JOBS ck_wrap $BUILD $mode $TYPE {1} {2} {3} $SHARDS {%} ::: ${ESM[*]} ::: ${AREA[*]} ::: $(seq -s ' ' $START $SHARDS) || exit -1
 	fi
 
-	# XXX: this is a mv which could affect a previs after a precombine if an archive isn't involved inbetween
-	if [[ "$mode" == "precombined" ]]; then
-		echo "Moving precombined..." 1>&2
-		mkdir -p "$OUT/Data/Meshes/PreCombined"
-		rsync --remove-source-files -avSP "$BUILD"/PreCombined.*/ "$OUT/Data/Meshes/PreCombined"/
-	elif [[ "$mode" == "previs" ]]; then
-		echo "Moving previs..." 1>&2
-		mkdir -p "$OUT/Data/Vis"
-		rsync --remove-source-files -avSP "$BUILD"/Vis.*/ "$OUT/Data/Vis"/
-	fi
+	for esm in ${ESM[*]}; do
+		# XXX: this is a mv which could affect a previs after a precombine if an archive isn't involved inbetween
+		if [[ "$mode" == "precombined" ]]; then
+			echo "Moving precombined for $esm..." 1>&2
+			for i in "$BUILD/$esm/PreCombined".*; do
+				mkdir -p "$OUT/$esm/Data/Meshes/PreCombined"
+				rsync --remove-source-files -aSP "$i"/ "$OUT/$esm/Data/Meshes/PreCombined"/ || true
+			done
+		elif [[ "$mode" == "previs" ]]; then
+			echo "Moving previs for $esm..." 1>&2
+			for i in "$BUILD/$esm/Vis".*; do
+				mkdir -p "$OUT/$esm/Data/Vis"
+				rsync --remove-source-files -aSP "$i"/ "$OUT/$esm/Data/Vis"/ || true
+			done
+		fi
 
-	mkdir -p "$OUT/plugins"
-	find "$BUILD" -type f -name 'CombinedObjects.*.esp' -o -name 'PreVis.*.esp' -print0 | xargs -r0 mv -nt "$OUT/plugins"
+		mkdir -p "$OUT/$esm/plugins"
+		find "$BUILD/$esm" -type f -name 'CombinedObjects.*.esp' -o -name 'PreVis.*.esp' -print0 | xargs -r0 mv -nt "$OUT/$esm/plugins"
+		find "$BUILD/$esm" -type d -print0 | xargs -r0 rmdir --ignore-fail-on-non-empty
 
-	if [[ -n "$MERGE" ]]; then
-		echo "Merging plugins..." 1>&2
-		# XXX: Plugins might have to be in Data first
-		# Could not parse command line properly.  Should be -CheckInPlugin:<PluginFilename> <ESMFilename>
-		find "$OUT/plugins" -type f -name '*.esp' -print0 \
-			| xargs -I{} -r0 -n1 ./CreationKit.exe -checkinplugin:{} $MERGE
-	fi
+		if ((MERGE)); then
+			echo "Merging plugins for $esm..." 1>&2
+
+			# XXX: Plugins might have to be in Data first
+			# Could not parse command line properly.  Should be -CheckInPlugin:<PluginFilename> <ESMFilename>
+			find "$OUT/$esm/plugins" -type f -name '*.esp' -print0 \
+				| xargs -I{} -r0 -n1 ./CreationKit.exe -checkinplugin:{} $esm
+		fi
+
+		if ((ARCHIVE)); then
+			echo "Archiving data for $esm..." 1>&2
+
+			# Output data will contain precombined and/or previs data only at this point
+			Tools/Archive2/Archive2.exe "$OUT/$esm/Data" -c="$OUT/$esm/${esm/.esm} - ckgen.ba2"
+		fi
+
+	done
 done
-
-if [[ -n "$ARCHIVE" ]]; then
-	echo "Archiving data..." 1>&2
-
-	# Output data will contain precombined and/or previs data only at this point
-	Tools/Archive2/Archive2.exe "$OUT/Data" -c="$OUT/$ARCHIVE"
-fi
